### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by ghost** [Harrietbrown/field_management#1]
Here you're asking the user for an integer input several times. This sort of situation is a great opportunity to write a function to avoid repeating yourself [D.R.Y concept](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself/wiki/Don%27t_repeat_yourself)
https://github.com/Harrietbrown/field_management/blob/73147b12d6b61b9a6002b753bd8e17fa1e211f3c/OOPbasics1/animal_manager.py#L49-L88

For example you could write a function like this:
````python 
def get_integer_from_user(min_val, max_val, message):
    ...
````
This has several advantages: the function name documents what a block of code is doing, it keeps your other methods brief and easy to read and makes unit testing easier.

**Comment by ghost** [comment]
I'm guessing you're using Python 3? Just letting you know in Python 2 when calling `super` you must specify some arguments. For the majority of cases you'l have 2 arguments: the *type* of object you want the superclass method of and then an *instance* of that object. For example in your Potato class: 
https://github.com/Harrietbrown/field_management/blob/73147b12d6b61b9a6002b753bd8e17fa1e211f3c/OOPbasics1/potato_class.py#L3-L10

The `super` call would become:
```python
super(Potato, self).__init__(1, 3, 6)
```
This is also valid code in Python 3, but since at Mantid we're supporting both we always specify these arguments.

**Comment by Harrietbrown** [comment]
Ok, I've changed my select option function to accept an message to print, so I can use that for all the cases where I need the user to input an integer.

I'll make a note of the arguments when calling super.

**Comment by ghost** [comment]
Overall I think this looks really good. You've got nice descriptive variable names and are obviously grasping classes and Python's data structures like lists and dictionaries. Good stuff 👍

**Comment by Harrietbrown** [comment]
Thanks

**Comment by ghost** [comment]
Just one-or-two small comments about style. Mantid follows the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guide, which is generally accepted as the Python standard. Mantid set out a couple of their own rules in their [guide](http://developer.mantidproject.org/Standards/PythonStandards.html#id1) as well. The PEP8 guide can be a bit tedious to read so I'll give you the main points:

- 2 lines separate module level (i.e. no indents) functions and classes
- 1 line separates class level functions
- Comments should all start '# ' (with a space after the '#')
- Surround assignment (=) and comparison (==, >=) operators with spaces e.g. `a >= b` not `a>=b`
- Spaces after commas in function definitions/calls e.g. `func(a, b)` not `func(a,b)`
- Avoid implicit imports e.g. instead of  `from my_module import *` use `from my_module import MyClass`

PyCharm is very good at picking up stuff like this and warning you about it. If you're not using PyCharm and need any help setting it up let me know.
